default:
  image: debian:trixie-slim

stages:
  - build

.build:
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    CROSS_COMPILE: aarch64-linux-gnu-
    ARCH: arm64
    GIT_STRATEGY: fetch
    GIT_DEPTH: "1"
    RKBIN_REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/hardware-enablement/rockchip-3588/rkbin.git
    RK3588_BL31_URL: https://gitlab.collabora.com/hardware-enablement/rockchip-3588/trusted-firmware-a/-/jobs/artifacts/rockchip/raw/build/rk3588/release/bl31/bl31.elf?job=build%20rk3588
  before_script:
    - apt update
    - apt install -y bc build-essential
                        crossbuild-essential-arm64
                        device-tree-compiler
                        git
                        python3
                        bison
                        flex
                        lzop
                        python3-setuptools
                        swig
                        python3-dev
                        libssl-dev
                        python3-pyelftools
                        uuid-dev
                        gnutls-dev
                        wget
  script:
    # download rkbin
    - git clone --depth 1 -b master ${RKBIN_REPO_URL} $CI_PROJECT_DIR/../rkbin
    # download upstream TF-A binaries generated by CI
    - mkdir -p ../trusted-firmware-a
    - wget -O ../trusted-firmware-a/rk3588-bl31.elf ${RK3588_BL31_URL}
    # build
    - cd $CI_PROJECT_DIR
    - make $BUILDCONFIG
    - make -j$(nproc)
    - ../rkbin/tools/boot_merger rock5b-rk3588.ini

    # build proprietary usb loader
    # the directory-dance here is because boot_merger shipped in rkbin
    # doesn't seem to support the "--prepath" option which is available in
    # downstream U-Boot.
    - cd ../rkbin && ./tools/boot_merger RKBOOT/RK3588MINIALL.ini && mv *spl_loader*.bin ../u-boot/

.build rock5b:
  extends: .build
  variables:
    BUILDCONFIG: rock5b-rk3588_defconfig
    ROCKCHIP_TPL: ../rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.18.bin
  artifacts:
    paths:
      - u-boot.itb
      - idbloader.img
      - u-boot-rockchip.bin
      - u-boot-rockchip-spi.bin
      - rock5b-rk3588.bin
      - rk3588_spl_loader_*.bin

build rock-5b with upstream TF-A:
  extends: .build rock5b
  variables:
    BL31: ../trusted-firmware-a/rk3588-bl31.elf

build rock-5b with vendor TF-A:
  extends: .build rock5b
  variables:
    BL31: ../rkbin/bin/rk35/rk3588_bl31_v1.47.elf
